name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Compile
        uses: docker://espressif/idf:release-v4.4
        with:
          args: /bin/bash -c "git config --global --add safe.directory /github/workspace && idf.py build"
