name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install test framework
        run: make -C tests install
      - name: Test
        run: make -C tests
      - name: Build coverage results
        run: |
          make -C tests gcov
          mkdir -p coverage_report
          cd coverage_report
          cp -R ../tests/gcov/*.gcov ./
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage_report
